 Deployment configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test13
  namespace: test13
  labels:
    app: test13
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test13
  template:
    metadata:
      labels:
        app: test13
    spec:
      containers:
      - name: test13
        image: alirathore412/react-weather-app:latest
        ports:
        - containerPort: 80
